on:
  workflow_call:
    inputs:
      exclude:
        default: ''
        required: false
        type: string
      pre-command:
        default: ''
        required: false
        type: string
    secrets:
      gh_token:
        required: false

env:
  gh_token: ${{ github.token }}

jobs:
  clang_tidy_review:
    runs-on: ubuntu-latest
    steps:
      # Check secret
      - name: "Check secrets.gh_token exists"
        id: check_secret
        shell: bash
        run: |
          if [ "${{ secrets.gh_token }}" != '' ]; then
            echo "secrets.gh_token is exist"
            echo "token=${{ secrets.gh_token }}" >> $GITHUB_OUTPUT
          else
            echo "secrets.gh_token is not exist. use github.token"
            echo "token=${{ env.gh_token }}" >> $GITHUB_OUTPUT
          fi

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ steps.check_secret.outputs.token }}

      - name: Run clang-tidy review
        uses: kimhyungrok/clang-tidy-action@v1.2.1
        with:
          exclude: ${{ inputs.exclude }}
          pre-command: ${{ inputs.pre-command }}
